### ISSUE TITLE
jquery dependency version.

### ISSUE THREAD

**Issue by kyuwoo-choi** [alexanderdickson/waitForImages#55]
I see it requires jQuery >= 1.8 refer to readme.md but bower.json has ~2.1.
Is it ok with 1.8 or should I grab 2.1? Having consistency will be great.

**Comment by alexanderdickson** [comment]
1.8 should be fine, but I switched the version dependency to suit [this issue](https://github.com/alexanderdickson/waitForImages/issues/47).

**Comment by kyuwoo-choi** [comment]
oh. then how about >=1.8 in package.json? 
as I know jesperronn's [issue](https://github.com/alexanderdickson/waitForImages/issues/47) is due to he's project has some other dependency requires 2.x jquery. so specifying >=1.8 will be fine.
As jquery 2.x officially dropped support for IE6/7/8, changing jquery version from 1.x to 2.x means waitForImages dropping support for those browsers too.
please consider keep supporting them.

**Comment by alexanderdickson** [comment]
Alrighty, let me take a look.

**Comment by alexanderdickson** [comment]
Pushing a fix for you now @kyuwoo-choi.

**Comment by kyuwoo-choi** [comment]
oh that's really cool :)
