### ISSUE TITLE
Release a new version with support of old jQuery

### ISSUE THREAD

**Issue by apsavin** [alexanderdickson/waitForImages#58]
Hi, Alex!
Can you please release a new version (2.0.1 ?) with support of jQuery 1.8 and higher?
I see the changes in the bower.json file, but it's not working without the release:

```
8) jquery#~2.1 which resolved to 2.1.3 and is required by waitForImages#2.0.0
```

**Comment by alexanderdickson** [comment]
Sure, I don't know how I stuffed that up.

**Comment by alexanderdickson** [comment]
I am about to tag and release 2.0.1.

**Comment by apsavin** [comment]
@alexanderdickson it seems that you forget to update bower.json file.

**Comment by alexanderdickson** [comment]
Whoops! Will do that now.
