### ISSUE TITLE
"eachCallback" should fire for cached images

### ISSUE THREAD

**Issue by apsavin** [alexanderdickson/waitForImages#60]
Hi!
eachCallback fires only for uncached images. It looks like a bug.

**Comment by alexanderdickson** [comment]
That's by design - we only want callback for images when they load.

If they're loaded, then we don't need to wait for them to load.

**Comment by apsavin** [comment]
ok, but, may be, it's worth to mention in the README.md?

**Comment by alexanderdickson** [comment]
I can do that.

**Comment by alexanderdickson** [comment]
Added a note.

https://github.com/alexanderdickson/waitForImages/commit/abe960e9a38e20a883436d885bfb17e3c2ab286a
