### ISSUE TITLE
selector don't seems to be respected

### ISSUE THREAD

**Issue by WillyBrownHair** [alexanderdickson/waitForImages#62]
I would like to use waitForImages only in a container. There is just one header css background-image inside, load dynamically xith php.

I check the console, It's seems to work on last version of chrome browser but not on Firefox and Safari. With these too last browser, the callback is execute only after all images <img> on the page are loaded.

I tried lot of modifications : 
- use an ID for the container instead of Class 
- use the specific hasImageProperties on my background-image div
...

my code: 

`
        <div class="inner-header" id="inner-header">						
            <div id="header-cover "class="header-cover cover" style="background-image:url(img.jpg);"></div>
        </div>
`

	$('.inner-header').waitForImages({

		    finished: function() {
		    	// my callback
			    }, 	
			    waitForAll: true

			});

Do you have any suggestion ?
Thanks for your work.

Willy

**Comment by benletchford** [comment]
+1

**Comment by alexanderdickson** [comment]
I would say @WillyBrownHair that you probably have a wrong selector as I used your code in this [fiddle](http://jsfiddle.net/mej17skd/) and was unable to reproduce your issue. Sometimes one of the other images has loaded before the main one, but it doesn't necessarily mean the code waited for *it* specifically.

If you can reproduce it in a fiddle, please let me know.

**Comment by WillyBrownHair** [comment]
My selector is the same of in your fiddle. Strange...
actually, on your exemple it's working but maybe I have this problem because of Lazy size plugin I use. I replace all 'src' attribute by 'data-src'. This would be the reason ?

Thanks

**Comment by WillyBrownHair** [comment]
Ok I found the problem. 
My header css background-image is change dynamically, when I try with a fix background-image url it seems to work like on your fiddle.

**Comment by alexanderdickson** [comment]
Cool, if you change the `background-image` dynamically, make sure you call `waitForImages()` _after_ you've updated the background.

**Comment by WillyBrownHair** [comment]
Yes, the plugin is call after the background-image change.

Actually, When I use a fixed background-image, it's the first element loaded and callback are execute just after. On another side, when I use a dynamic background-image, it's loaded after all img inside the new content load with ajax. The selector i'snt respected.

Can I send you the link of my project by e-mail ?
Thanks

**Comment by alexanderdickson** [comment]
Sure thing.
