### ISSUE TITLE
waitForImages on same ID after images of container have been replaced

### ISSUE THREAD

**Issue by ratnanil** [alexanderdickson/waitForImages#63]
Hey man,

Great tool, I was screening the web exactly for this and foud it via stackexchange.

Now here's my situation: I have container (named "#carrier") which is populated with a series of `<img>`'s depending on a user selection. If the user makes a new selection, the old images are removed and a new series is created.

It seems that "waitForImages" only works the first time it checks the container "#carrier", the subsequent times it doen't realize that the images have changed. Is there a workaround for this problem? A way to clear the "memory" of "waitForImages"? Or am I on the wrong track?

Here's my code: http://ratnanil.github.io/reh_homerange/#

**Comment by alexanderdickson** [comment]
You should, on clearing of the contents of the element, be able to call `waitForImages()` again to get a new callback called when the descendant images have loaded.
