### ISSUE TITLE
Wait for images from the same domain only or only for background CSS images

### ISSUE THREAD

**Issue by thehappycoder** [alexanderdickson/waitForImages#66]
I use waitForImages to reveal the webpage only after all background CSS and img finish loading. But some images are from other host.

It would be good to have the following features:
1. Wait for images from the same domain only
2. Wait for background CSS images only

**Comment by alexanderdickson** [comment]
I don't think the first feature is common enough to warrant putting an option in for.

The second feature is potentially in the same bucket.

However, I could put a *custom selector* or filter function as part of the configuration options, which would let you filter out images/elements as you please.

**Comment by thehappycoder** [comment]
That would be very useful.

**Comment by alexanderdickson** [comment]
Feel free to submit a PR, I probably won't get to this for a few weeks.

**Comment by thehappycoder** [comment]
I think this may be problematic due to this issue http://www.scriptscoop.net/t/c46d8374dec2/javascript-prevent-downloading-background-image-when-parent-is-hidden-and-css-of-.html

Shortly, when you call .css on an element, it triggers background image downloading (at least on google chrome it's like that).

**Comment by alexanderdickson** [comment]
I didn't think of this previously, but shouldn't it be simple to select only the elements you want using jQuery?

> 1. Wait for images from the same domain only

```
$("img").filter(function() {
  var a = $("<a />", { href: this.src })[0]: 
  return a.host === window.location.host;
}).waitForImages();

```
2. Wait for background CSS images only

`$(".div").not("img").waitForImages();`

One would assume you're not trying to set background images for `img` elements.
