### ISSUE TITLE
wait for images, only above the fold would be an awesome asset for database driven parallax spa's

### ISSUE THREAD

**Issue by r3wt** [alexanderdickson/waitForImages#68]
the reason we need this is so we can get an accurate position to scroll to. your plugin works, but it requires us to check then entire div, which could have a ton of images below the fold, which leads to noticeable delays. i have written quite a bit of javascript code for detecting the positioning of elements in the documents. is there a method for integrating custom logic into waitForImages? i need to use some of my custom jQuery expressions to wait for only image above the fold in the target div.I read the documentation and it wasn't immediately clear how i could do this.

**Comment by alexanderdickson** [comment]
Sorry, right now there isn't, but I can see that being useful. I will add something like that in the new release.

**Comment by alexanderdickson** [comment]
Is it possible to only select the images you want to wait for up front? 

Something like:

   $("img").filter(function() { return $(this).offset().top < $(window).height(); }).waitForImages();
