### ISSUE TITLE
Add a destroy capability

### ISSUE THREAD

**Issue by nevf** [alexanderdickson/waitForImages#69]
I am developing an app [Clibu](http://www.clibu.com) which uses waitForImages. The element containing the images can be removed from the dom, before waitForImages completes. In this scenario I'd like a way to cleanup the `img.on('load')` event handles that waitForImages adds. 

I've looked through the code and reads the doc's and can't see a way to accomplish this.

**Comment by alexanderdickson** [comment]
That's a good idea. I can add something to do that.

**Comment by nevf** [comment]
@alexanderdickson Great, many thanks.

**Comment by chaddugas** [comment]
I would also really like this.  I am using this on a search feature that hides the page content and displays the search results.  If the search is done before the original page content finishes loading, the search result images won't display. 

Thanks.

**Comment by nevf** [comment]
@alexanderdickson Just wondering if you've made any progress on this.

**Comment by alexanderdickson** [comment]
@nevf I will get to it soon, I have some time. As a temporary workaround, you can use `off(". waitForImages")` on the elements it binds to and it should work.

**Comment by alexanderdickson** [comment]
@nevf I decided it's more complicated than I thought, due to the fact that the events are not attached directly to DOM elements, but image elements created for the purpose of detecting if they're loaded.

I am planning on doing a bit re-write soon, to drop the jQuery dependency and to add a few other bits. When I do that, I can do this.

**Comment by haqqi** [comment]
I like this plugin, and seems like i need this feature too.

**Comment by alexanderdickson** [comment]
Can someone provide some example code of why a _destroy_ is needed?

Is it because if you call it, but then remove the images from the DOM before they're loaded, they will still be loaded?

This plugin shouldn't add any events to existing elements in the DOM.

**Comment by alexanderdickson** [comment]
Closing because of problem not clearly stated.

If anyone can come up with a jsFiddle or similar demonstrating the problem I'll relook into this.
