### ISSUE TITLE
Publish as an npm package

### ISSUE THREAD

**Issue by cprecioso** [alexanderdickson/waitForImages#74]
Hi, it'd be much easier for my (and I suppose other's) workflow if you could publish this as a `npm` package. Judging by the `package.json`, it should be simply a matter of doing an `npm publish`. Thank you.

**Comment by alexanderdickson** [comment]
I can do that.

**Comment by alexanderdickson** [comment]
[Done](https://www.npmjs.com/package/jquery.waitforimages)!
