### ISSUE TITLE
Image with empty square box consider image loaded?

### ISSUE THREAD

**Issue by ahgan84** [alexanderdickson/waitForImages#77]
hi there, my topic here is the same: http://stackoverflow.com/questions/39159805/wait-for-image-to-load-plugin-not-functioning

Below is my code:

```
    $('.marquee').waitForImages(function() {
    console.log('All images have loaded.');
    setTimeout(startMarquee);
}, function(loaded, count, success) {
   console.log(loaded + ' of ' + count + ' images has ' + (success ? 'loaded' : 'failed to load') +  '.');
   $(this).addClass('loaded');
}); 
```

I will start a marquee scrolling of images when the images is loaded complete.

My problem is, some images had not yet load but just show a small empty square box,
the plugin also consider it already load. Any idea how to fix it?

Does showing a small empty square box only is consider image loaded?

**Comment by alexanderdickson** [comment]
Can you show me the HTML too please so I don't make any false assumptions? Perhaps on jsfiddle or similar?

**Comment by alexanderdickson** [comment]
Closing due to no response from OP.
