### ISSUE TITLE
Images are loaded twice when using srcset with width descriptor

### ISSUE THREAD

**Issue by anjanina** [alexanderdickson/waitForImages#81]
I'm not sure if #64 fixes only srcset attributes that include densitiy descriptors (1x, 2x)?.  I use the srcset attribute with width descriptor and the browser always loads two images.
E.g.
`<img src="{url}/s,x,586,y,0/{img_id}" 
  srcset="{url}/s,x,293,y,0/{img_id} 293w,  {url}/s,x,440,y,0/{img_id} 440w, 
{url}/s,x,586,y,0/{img_id} 586w"
sizes="(max-width: 520px) 100vw,  15vw" />`

I use the plugin this way:
`$(element).waitForImages({  
    finished: function() {...},  
    waitForAll: true
});`

$(element) has two descendant images that should be loaded before some adjustments take place.

Thanks in advance

**Comment by asadkn** [comment]
I noticed this today and created a patch: (only tested in Safari 9, Chrome and Firefox - you might wish to test in IE): https://github.com/asadkn/waitForImages/blob/847d98efb87f6dc8d0cff693c422ab8e9b02725f/src/jquery.waitforimages.js

**Comment by moesfeld** [comment]
Hi,
thanks for the patch. I tested it and it works for me on Safari, Chrome, Firefox and Edge. On IE11 however it does not work. This is my img:

`<img src="http://127.0.0.1:81/media/image/thumbnail/Product-Splash_480x480.jpg"
srcset="media/image/thumbnail/Product-Splash_768x768.jpg 768w,
media/image/thumbnail/Product-Splash_512x512.jpg 512w,
media/image/thumbnail/Product-Splash_640x640.jpg 640w,
media/image/thumbnail/Product-Splash_140x140.jpg 140w" 
sizes="(min-width: 768px) 50vw, 100vw">`

With kind regards

**Comment by alexanderdickson** [comment]
Thanks, I will look into incorporating the patch now.

**Comment by alexanderdickson** [comment]
@moesfeld Check the current master, does it solve your problems?

**Comment by Shirkit** [comment]
@alexanderdickson I came up with the simplest example I could come up with here: https://codepen.io/shirkit/pen/yPrjgX

If you open the Network tab on Chrome or Firefox, you'll see that in both browsers, it loads the original img:src attribute, and the the one correctly choosen by the browser.

But that does not mean we have the cause. I further studied what might be causing the issue, and I created 2 local HTML files to test the theory: https://gist.github.com/Shirkit/d19b506b044859d85e2e3ccb3d9f61d6

- The first file **test.html** shows the issue happening, but the script waitForImages is being loaded async.
- The second file **test2.html** does not reproduce the issue, as everything is inlined in the HTML.

I could reproduce the issue whenever running some kind of async loading, as in `script defer`, `script async`, or some kind of js async loading.

I failed to persue the issue any longer after that, couldn't trace down the origin of the bug.

Hope this helps.

**Comment by Shirkit** [comment]
So, I was wrong before @alexanderdickson the problem can be even further reduced. Wrapping the waitForImages in a `jQuery(window).ready` will manifest the problem.

Just look at the example below, if you run locally, the plugin will try to load an incorret image.

https://gist.github.com/Shirkit/de1a1d9d35971e77b602e35589688b6c
