### ISSUE TITLE
302 redirect is not waited

### ISSUE THREAD

**Issue by marconline** [alexanderdickson/waitForImages#82]
Hello, I think that I found a wrong (?) behavior.
If my image url redirects (HTTP 302) to another url, a load event is fired as soon as the 302 request has been received and not when the redirection is completed. Is that normal?

Thanks,
Marco

**Comment by alexanderdickson** [comment]
I'm not sure. Although I think it should be handled by the browser - I am simply leveraging the `load` event on `img` elements for this plugin.

Anyway it's not something that's worth trying to code around (e.g. to use XHR first on the image, will only work on same-domain etc) so I will close this.
