### ISSUE TITLE
plugin doesn't work when images are wrapped in a display none element

### ISSUE THREAD

**Issue by medBouzid** [alexanderdickson/waitForImages#86]
Hi, 
The plugin seems to work only on visible images, if the image is wrapped in a div or span that has a display none style the "loaded" won't be triggered... sometimes we need to hide images and show a progress bar or spinner until the loading is complete and only then show the image.. any quick fix for this ?

Thanks

**Comment by alexanderdickson** [comment]
It should still work in that situation.

Can you reduce it down to a basic test case?
