### ISSUE TITLE
Dist files displays the wrong version

### ISSUE THREAD

**Issue by ankushdharkar** [alexanderdickson/waitForImages#87]
The release page says `2.2.0`, but the `jquery.waitforimages.js` in **dist** says `2.1.0`

```
/*! waitForImages jQuery Plugin - v2.1.0 - 2016-01-04
* https://github.com/alexanderdickson/waitForImages
* Copyright (c) 2016 Alex Dickson; Licensed MIT */
```

**Comment by alexanderdickson** [comment]
Can fix soon - or send a PR :smile:

**Comment by Thunderforge** [comment]
[Looks like this is already fixed](https://github.com/alexanderdickson/waitForImages/blob/91bc990cfeba31d2fe105834c53ccb8a0e8bbd57/dist/jquery.waitforimages.js#L1).
