### ISSUE TITLE
Time for a NPMJS release ?

### ISSUE THREAD

**Issue by ambroisemaupate** [alexanderdickson/waitForImages#92]
Hi @alexanderdickson 

We would like to know do you plan to release a new tagged version with all the enhancements for 2 years. It would be great to get it from npmjs.

`yarn add jquery.waitforimages` or `npm install --save jquery.waitforimages` are still downloading 2.2.0 tag.

Thanks !

**Comment by ambroisemaupate** [comment]
It would be cool for next updates that `.travis-ci.yml` includes a **push-npm** stage to automatically push on npmjs.com at each new *tag*.

**Comment by alexanderdickson** [comment]
Thanks @ambroisemaupate I will do that now
